name: PR Code Checks

on:
  pull_request:
    branches: ["main", "dev"]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  tox
    - name: Formatting
      run: tox -e format
    - name: Linting
      run: tox -e lint
    - name: Type Checking
      run: tox -e typing
  test:
    runs-on: ubuntu-latest
    env:
      ENV: test
      DYNACONF_MONGODB__PASSWORD: ${{ secrets.MONGODB__PASSWORD }}
      DYNACONF_HEVY_API__KEY: ${{ secrets.HEVY_API__KEY }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  tox 
    - name: Unit Tests
      run: tox -e py