name: PR Code Checks

on:
  pull_request:
    branches: ["main", "dev"]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  tox ty ruff~=0.12.0
    - name: Formatting
      run: ruff format --check
    - name: Linting
      run: ruff check
    - name: Type Checking
      run: tox -e typing
  test:
    runs-on: ubuntu-latest
    env:
      ENV: test
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  tox pytest pytest-asyncio pytest-cov
    - name: Unit Tests
      run: tox -e py
    - name: Integration Tests
      run: tox -e intg